name: CI python

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - gpl769_use_cherrypicked_view

env: 
  UNIFIED_WAREHOUSE_IMAGE: docker.pkg.github.com/sanger/unified_warehouse/unified_warehouse:develop
  EVENT_WAREHOUSE_IMAGE: docker.pkg.github.com/sanger/event_warehouse/event_warehouse:master
jobs:
  test_job:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.2.5
        ports:
          - 27017:27017
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: null
          MYSQL_DATABASE: unified_warehouse_test
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: MyS3cr3tPassw0rd
      rmq:
        image: rabbitmq:3
        ports:
          - 5672:5672
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
      ewh:
        image: ${EVENT_WAREHOUSE_IMAGE}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          DBHOST: mysql
          RMQHOST: rmq
          INTEGRATION_TEST_SETUP: true
          RAILS_ENV: test
      uwh:
        image: ${UNIFIED_WAREHOUSE_IMAGE}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          DBHOST: mysql
          RMQHOST: rmq
          INTEGRATION_TEST_SETUP: true
          RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies
        run: |
          pipenv install --dev --ignore-pipfile --system --deploy
      - name: Check format with black
        run: |
          # stop the build if there are black formatting errors
          python -m black --check .
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8
      - name: Run mypy
        run: |
          python -m mypy .
      - name: Create SQL Server testing database
        run: |
          python setup_sqlserver_test_db.py
      - name: Test with pytest
        run: |
          python -m pytest -x
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
